### ISSUE TITLE
Taille des fichiers générés par webpack

### ISSUE THREAD

**Issue by adjm-fr** [jhoareau/ctn-website#10]
Il faudrait peut-être essayer de limiter la taille des fichiers générés par webpack ?

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (250 kB).
This can impact web performance.
Assets:
  fontawesome-webfont.svg (444 kB)
  bundle.js (7.94 MB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (250 kB). This can impact web performance.
Entrypoints:
  main (7.94 MB)
      bundle.js

WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

**Comment by jhoareau** [comment]
- Faire une configuration Webpack de développement et de production
- Migration HTTP/2 ?

**Comment by jhoareau** [comment]
Configuration de Webpack en production: done
HTTP/2 : pas compatible avec la configuration actuelle nginx ECLAIR
