### ISSUE TITLE
A propos

### ISSUE THREAD

**Issue by adjm-fr** [jhoareau/ctn-website#7]
Juste une page statique donc ? Avec un CSS bien swag, à voir avec les membres de CTN

**Comment by adjm-fr** [comment]
Qu'est-ce qu'on peut utiliser pour faire un truc swag ? Un truc sur PS, ça passe ?

**Comment by jhoareau** [comment]
Sans doute un truc avec des typos sympa, demande un texte à CTN

**Comment by jhoareau** [comment]
Ca arrive pour la release
