### ISSUE TITLE
Page admin

### ISSUE THREAD

**Issue by adjm-fr** [jhoareau/ctn-website#8]
- Pouvoir gérer les news, les vidéos et le matos depuis cette page.
- Avoir un fil d'actualité pour le matos, retraçant chaque action (sans doute délicat ? quoique y'a le field 'historique' dans mongo ?)

**Comment by jhoareau** [comment]
Déjà en cours

**Comment by ADJMLyon** [comment]
En cours, pas done, donc pas closed :p
