### ISSUE TITLE
Carousel

### ISSUE THREAD

**Issue by adjm-fr** [jhoareau/ctn-website#9]
- Frontend + vérification format image à l'upload
- Améliorer le CSS
- Ajout d'un switch de news temporel
- Limiter à un certain nombre de news ?
- Rajouter la possibilité de liens externes ?

**Comment by jhoareau** [comment]
Switch de news temporel ?

**Comment by adjm-fr** [comment]
autoplay, done

**Comment by adjm-fr** [comment]
Field 'link' dans le schema 'News' de mongo, qui sera le src du title !

**Comment by jhoareau** [comment]
Frontend done

Il reste à faire la route
